# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'Badi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Badi
  pod 'Kingfisher'
  pod 'TinyConstraints' 

  target 'BadiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
